/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeituraRouteImport } from './routes/leitura'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationStationIdRouteImport } from './routes/station.$stationId'

const LeituraRoute = LeituraRouteImport.update({
  id: '/leitura',
  path: '/leitura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationStationIdRoute = StationStationIdRouteImport.update({
  id: '/station/$stationId',
  path: '/station/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leitura': typeof LeituraRoute
  '/station/$stationId': typeof StationStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leitura': typeof LeituraRoute
  '/station/$stationId': typeof StationStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leitura': typeof LeituraRoute
  '/station/$stationId': typeof StationStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leitura' | '/station/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leitura' | '/station/$stationId'
  id: '__root__' | '/' | '/leitura' | '/station/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeituraRoute: typeof LeituraRoute
  StationStationIdRoute: typeof StationStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leitura': {
      id: '/leitura'
      path: '/leitura'
      fullPath: '/leitura'
      preLoaderRoute: typeof LeituraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$stationId': {
      id: '/station/$stationId'
      path: '/station/$stationId'
      fullPath: '/station/$stationId'
      preLoaderRoute: typeof StationStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeituraRoute: LeituraRoute,
  StationStationIdRoute: StationStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
